version: '3'
services:
  web:
    entrypoint: node server.js
    image: $REGISTRY/cep-auto-scaler:latest
    networks:
      - router_network
      - auto-scaler-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role == manager"
  mongo:
    image: $REGISTRY/alpine-mongo:latest
    networks:
      - auto-scaler-network
networks:
  auto-scaler-network:
  router_network:
    external: true
